apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: manifests
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/matheus3301/simplest-homelab.git
        revision: HEAD
        directories:
          - path: gitops/*/*
  template:
    metadata:
      name: >-
        {{- $layer := index (splitList "/" .path.path) 1 -}}
        {{- $component := index (splitList "/" .path.path) 2 -}}
        {{- if hasPrefix "01-" $layer }}core{{- else if hasPrefix "02-" $layer }}services{{- else }}apps{{- end }}-{{ $component }}-manifests
      namespace: argocd
    spec:
      project: '{{- $layer := index (splitList "/" .path.path) 1 -}}{{- if hasPrefix "01-" $layer }}core{{- else if hasPrefix "02-" $layer }}services{{- else }}apps{{- end }}'
      source:
        repoURL: https://github.com/matheus3301/simplest-homelab.git
        targetRevision: HEAD
        path: '{{ .path.path }}'
        directory:
          exclude: '*-Application.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .path.basename }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
