apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: istiod
  namespace: istio-system
spec:
  endpoints:
    - port: http-monitoring
      path: /metrics
  selector:
    matchLabels:
      app: istiod
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: istio-gateways
  namespace: istio-system
spec:
  podMetricsEndpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
  selector:
    matchExpressions:
      - key: gateway.istio.io/managed
        operator: Exists
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: ztunnel
  namespace: istio-system
spec:
  podMetricsEndpoints:
    - port: ztunnel-stats
      path: /metrics
  selector:
    matchLabels:
      app: ztunnel
