apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-mmonteiro-dev
  namespace: istio-system
spec:
  secretName: wildcard-mmonteiro-dev-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - "*.mmonteiro.dev"
    - "mmonteiro.dev"
