apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tunnel-token
  namespace: cloudflared
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: tunnel-token
  data:
    - secretKey: token
      remoteRef:
        key: secret/cloudflared/tunnel-token
        property: token
